# rejection sampling.R
# Take a sample from a large population generated by make.population.R
# Randall Johnson
# BSP CCR Genetics Core at Frederick National Laboratory
# SAIC-Frederick, Inc
# Created August 1, 2013
# Last Modified August 1, 2013


if(biowulf)
{
    load('~/mald/map.RData')
}else{
    load('map.RData')
}


######################
# Rejection Sampling #
######################

set.seed(args$seed)

risk.allele <- sample(map$SNP[map$CHR != 23], size = 1)

anc$risk <- (anc[[paste(risk.allele, 1, sep = '.')]] == 1) + (anc[[paste(risk.allele, 2, sep = '.')]] == 1)

# pick controls (uniformly) first so rejection sampling doesn't skew this group
controls <- sample(anc$id, size = args$n)

# pick cases proportional to their ancestry at the risk allele
cases <- with(subset(anc, !id %in% controls), sample(id, size = args$n,
                                                     prob = args$risk^risk*A0*c / (args$risk^risk*A0*c + (1 - A0))))

to.keep <- c(cases, controls)

anc <- subset(anc, id %in% to.keep)
anc$case <- anc$id %in% cases

attributes(anc)$seed <- args$seed
attributes(anc)$risk.allele <- args$risk.allele
attributes(anc)$risk <- args$risk

########################################
# Fix X chromosome genotypes for males #
########################################
sexChrom <- map$SNP[map$CHR == 23]
male <- which(anc$gender == 'M')

for(rs in sexChrom)
{
    anc[[rs]][male] <- ifelse(anc[[rs]][male] == 1, 2, anc[[rs]][male])
}
