# simsMaster.R
# All simulation-related scripts
# Randall Johnson
# BSP CCR Genetics Core at Frederick National Laboratory
# Leidos Biomedical Research, Inc
# Created May 27, 2014
# Last Modified May 27, 2014


# Simulate population from which to sample
source('make.population.R')

# Join disperate files created in make.population.R into one data file
source('join.populations.R')

# Take a sample from a large population generated by make.population.R
source('sample.population.R')

# Run the simulated data sets generated in sample.populations.R
source('run.sims.R')

# Do all inferrence testing for simulated data sets
source('test.sims.R')
